#!/bin/bash

domain="$1"
subdomain="$2"

get_record_info() {
    sub_domain="$1"
    dig_output=$(dig $sub_domain.$domain | awk '/^;; ANSWER SECTION:/{getline; print}')
    record_type=$(echo "$dig_output" | awk '{print $3}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_record_info "$sub"
    done
else
    get_record_info "$subdomain"
fi
