#!/bin/bash

sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid



#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

#!/bin/bash
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
service nginx restart
echo "" | dd status=none of=/run/nginx.pid
