#!/usr/bin/env bash
# a script that prints 'Best School' 10 times, for the 9th iteration 'Hi' will be printed as well
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done